"""A school admin's code remembers whose it is and which account it made.

A school administrator now signs in with their ten-digit code and nothing
else. That needs two things the code could not previously hold:

  label       who the code is for, given when it is issued. An account has to
              be called something, and a code cannot invent a name.
  claimed_by  the account it created. Entering the code a second time must
              return to the SAME administrator rather than making another —
              the rule the class register learned expensively, where hiding a
              claimed name meant signing out destroyed the account.

Both nullable, so codes issued before this keep working and an unredeemed one
simply has neither yet.

Written by hand rather than autogenerated: the change is two columns, and a
migration you can read is worth more than one you have to trust.

Revision ID: 0002_admin_code_identity
Revises: 0001_initial
"""
from alembic import op

revision = "0002_admin_code_identity"
down_revision = "0001_initial"
branch_labels = None
depends_on = None


def upgrade():
    op.execute('ALTER TABLE teacher_codes ADD COLUMN label VARCHAR(120)')
    op.execute('ALTER TABLE teacher_codes ADD COLUMN claimed_by INTEGER')
    op.execute('CREATE INDEX ix_teacher_codes_claimed_by '
               'ON teacher_codes (claimed_by)')


def downgrade():
    op.execute('DROP INDEX IF EXISTS ix_teacher_codes_claimed_by')
    op.execute('ALTER TABLE teacher_codes DROP COLUMN IF EXISTS claimed_by')
    op.execute('ALTER TABLE teacher_codes DROP COLUMN IF EXISTS label')
